### ISSUE TITLE
not a good idea to name the file "streamlit.py"

### ISSUE THREAD

**Issue by mallibus** [shaildeliwala/experiments#2]
The first time I executed your code  I got a strange error:
```
Traceback (most recent call last):
File "streamlit.py", line 2, in <module>
import streamlit as st
File "C:\Users\emamorc\Google Drive\AIML\Projects\streamlit.py", line 5, in <module>
@st.cache
AttributeError: partially initialized module 'streamlit' has no attribute 'cache' (most likely due to a circular import)
```
After some research I realized that the problem was the file name! changing the name from streamlit.py to demosl.py the error disappears.

**Comment by mallibus** [comment]
sorry I was running the app executing the file as a python file, not running with streamlit run streamlit.py
